import {
  Activity,
  AlertTriangle,
  ArrowDownCircle,
  ArrowUpCircle,
  Bell,
  Calendar as CalendarIcon,
  CheckCircle2,
  FileText,
  FolderKanban,
  Repeat,
  Sparkles,
  Target,
  TrendingUp,
  Trophy,
  Users,
  Video,
  Wallet,
} from "lucide-react";
import type { WidgetMeta } from "./types";

export const widgetRegistry: Record<string, WidgetMeta> = {
  "receita-mes": {
    type: "receita-mes",
    title: "Receita do mês",
    description: "Total faturado no mês corrente",
    category: "Financeiro",
    defaultSize: "sm",
    icon: Wallet,
  },
  "lucro-mes": {
    type: "lucro-mes",
    title: "Lucro do mês",
    description: "Lucro líquido e margem",
    category: "Financeiro",
    defaultSize: "sm",
    icon: TrendingUp,
  },
  "receita-recorrente": {
    type: "receita-recorrente",
    title: "A receber (previsto)",
    description: "Lançamentos futuros de receita",
    category: "Financeiro",
    defaultSize: "sm",
    icon: Repeat,
  },
  "contas-receber": {
    type: "contas-receber",
    title: "Contas a receber",
    description: "Próximos recebimentos previstos",
    category: "Financeiro",
    defaultSize: "sm",
    icon: ArrowDownCircle,
  },
  "contas-pagar": {
    type: "contas-pagar",
    title: "Contas a pagar",
    description: "Despesas a vencer",
    category: "Financeiro",
    defaultSize: "sm",
    icon: ArrowUpCircle,
  },
  "faturamento-grafico": {
    type: "faturamento-grafico",
    title: "Faturamento × Custos",
    description: "Comparativo de 6 meses",
    category: "Financeiro",
    defaultSize: "lg",
    icon: TrendingUp,
  },
  "indicadores-financeiros": {
    type: "indicadores-financeiros",
    title: "Indicadores",
    description: "Visão completa do financeiro",
    category: "Financeiro",
    defaultSize: "md",
    icon: Activity,
  },

  pipeline: {
    type: "pipeline",
    title: "Pipeline comercial",
    description: "Valor total no funil",
    category: "Comercial",
    defaultSize: "sm",
    icon: Target,
  },
  "leads-quentes": {
    type: "leads-quentes",
    title: "Leads quentes",
    description: "Negociações com maior valor",
    category: "Comercial",
    defaultSize: "lg",
    icon: Sparkles,
  },
  "propostas-aguardando": {
    type: "propostas-aguardando",
    title: "Propostas aguardando",
    description: "Enviadas sem resposta",
    category: "Comercial",
    defaultSize: "md",
    icon: FileText,
  },
  "clientes-ativos": {
    type: "clientes-ativos",
    title: "Clientes no CRM",
    description: "Base de clientes vigente",
    category: "Comercial",
    defaultSize: "sm",
    icon: Users,
  },
  followups: {
    type: "followups",
    title: "Follow-ups",
    description: "Próximas ações comerciais",
    category: "Comercial",
    defaultSize: "md",
    icon: Bell,
  },

  "projetos-ativos": {
    type: "projetos-ativos",
    title: "Projetos ativos",
    description: "Em produção no momento",
    category: "Operacional",
    defaultSize: "sm",
    icon: FolderKanban,
  },
  "projetos-criticos": {
    type: "projetos-criticos",
    title: "Projetos críticos",
    description: "Atrasados ou em risco",
    category: "Operacional",
    defaultSize: "md",
    icon: AlertTriangle,
  },
  "tarefas-pendentes": {
    type: "tarefas-pendentes",
    title: "Tarefas pendentes",
    description: "Tudo que precisa sair",
    category: "Operacional",
    defaultSize: "md",
    icon: CheckCircle2,
  },
  "proximas-gravacoes": {
    type: "proximas-gravacoes",
    title: "Próximas gravações",
    description: "Captações agendadas",
    category: "Operacional",
    defaultSize: "md",
    icon: Video,
  },

  "meu-dia": {
    type: "meu-dia",
    title: "Meu dia",
    description: "Compromissos e tarefas de hoje",
    category: "Pessoal",
    defaultSize: "md",
    icon: CalendarIcon,
  },
  agenda: {
    type: "agenda",
    title: "Agenda",
    description: "Próximos compromissos",
    category: "Pessoal",
    defaultSize: "md",
    icon: CalendarIcon,
  },
  "ultimas-atividades": {
    type: "ultimas-atividades",
    title: "Últimas atividades",
    description: "Feed do CRM",
    category: "Pessoal",
    defaultSize: "md",
    icon: Activity,
  },
  metas: {
    type: "metas",
    title: "Metas",
    description: "Progresso das metas do mês",
    category: "Pessoal",
    defaultSize: "md",
    icon: Trophy,
  },

  assistant: {
    type: "assistant",
    title: "MakersHub Assistant",
    description: "Assistente IA contextual",
    category: "Inteligência",
    defaultSize: "md",
    icon: Sparkles,
  },
};

export const widgetCatalog = Object.values(widgetRegistry);
