/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PropostasRouteImport } from './routes/propostas'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as OrcamentosRouteImport } from './routes/orcamentos'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ContratosRouteImport } from './routes/contratos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ComercialRouteImport } from './routes/comercial'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjetosIndexRouteImport } from './routes/projetos.index'
import { Route as OrcamentosIndexRouteImport } from './routes/orcamentos.index'
import { Route as FinanceiroIndexRouteImport } from './routes/financeiro.index'
import { Route as ComercialIndexRouteImport } from './routes/comercial.index'
import { Route as BibliotecaIndexRouteImport } from './routes/biblioteca.index'
import { Route as ProjetosIdRouteImport } from './routes/projetos.$id'
import { Route as OrcamentosNovoRouteImport } from './routes/orcamentos.novo'
import { Route as OrcamentosIdRouteImport } from './routes/orcamentos.$id'
import { Route as FinanceiroProjetosRouteImport } from './routes/financeiro.projetos'
import { Route as FinanceiroLancamentosRouteImport } from './routes/financeiro.lancamentos'
import { Route as FinanceiroContasRouteImport } from './routes/financeiro.contas'
import { Route as ComercialLeadsRouteImport } from './routes/comercial.leads'
import { Route as ComercialFollowupsRouteImport } from './routes/comercial.followups'
import { Route as ComercialEmpresasRouteImport } from './routes/comercial.empresas'
import { Route as ComercialContatosRouteImport } from './routes/comercial.contatos'
import { Route as ComercialAgendaRouteImport } from './routes/comercial.agenda'
import { Route as BibliotecaCategoriaRouteImport } from './routes/biblioteca.$categoria'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const PropostasRoute = PropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosRoute = OrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosRoute = ContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ComercialRoute = ComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjetosRoute,
} as any)
const OrcamentosIndexRoute = OrcamentosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrcamentosRoute,
} as any)
const FinanceiroIndexRoute = FinanceiroIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceiroRoute,
} as any)
const ComercialIndexRoute = ComercialIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComercialRoute,
} as any)
const BibliotecaIndexRoute = BibliotecaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BibliotecaRoute,
} as any)
const ProjetosIdRoute = ProjetosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjetosRoute,
} as any)
const OrcamentosNovoRoute = OrcamentosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => OrcamentosRoute,
} as any)
const OrcamentosIdRoute = OrcamentosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrcamentosRoute,
} as any)
const FinanceiroProjetosRoute = FinanceiroProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroLancamentosRoute = FinanceiroLancamentosRouteImport.update({
  id: '/lancamentos',
  path: '/lancamentos',
  getParentRoute: () => FinanceiroRoute,
} as any)
const FinanceiroContasRoute = FinanceiroContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => FinanceiroRoute,
} as any)
const ComercialLeadsRoute = ComercialLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => ComercialRoute,
} as any)
const ComercialFollowupsRoute = ComercialFollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => ComercialRoute,
} as any)
const ComercialEmpresasRoute = ComercialEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => ComercialRoute,
} as any)
const ComercialContatosRoute = ComercialContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => ComercialRoute,
} as any)
const ComercialAgendaRoute = ComercialAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => ComercialRoute,
} as any)
const BibliotecaCategoriaRoute = BibliotecaCategoriaRouteImport.update({
  id: '/$categoria',
  path: '/$categoria',
  getParentRoute: () => BibliotecaRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/comercial': typeof ComercialRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/contratos': typeof ContratosRoute
  '/crm': typeof CrmRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/orcamentos': typeof OrcamentosRouteWithChildren
  '/performance': typeof PerformanceRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/propostas': typeof PropostasRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/biblioteca/$categoria': typeof BibliotecaCategoriaRoute
  '/comercial/agenda': typeof ComercialAgendaRoute
  '/comercial/contatos': typeof ComercialContatosRoute
  '/comercial/empresas': typeof ComercialEmpresasRoute
  '/comercial/followups': typeof ComercialFollowupsRoute
  '/comercial/leads': typeof ComercialLeadsRoute
  '/financeiro/contas': typeof FinanceiroContasRoute
  '/financeiro/lancamentos': typeof FinanceiroLancamentosRoute
  '/financeiro/projetos': typeof FinanceiroProjetosRoute
  '/orcamentos/$id': typeof OrcamentosIdRoute
  '/orcamentos/novo': typeof OrcamentosNovoRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/biblioteca/': typeof BibliotecaIndexRoute
  '/comercial/': typeof ComercialIndexRoute
  '/financeiro/': typeof FinanceiroIndexRoute
  '/orcamentos/': typeof OrcamentosIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contratos': typeof ContratosRoute
  '/crm': typeof CrmRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/performance': typeof PerformanceRoute
  '/propostas': typeof PropostasRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/biblioteca/$categoria': typeof BibliotecaCategoriaRoute
  '/comercial/agenda': typeof ComercialAgendaRoute
  '/comercial/contatos': typeof ComercialContatosRoute
  '/comercial/empresas': typeof ComercialEmpresasRoute
  '/comercial/followups': typeof ComercialFollowupsRoute
  '/comercial/leads': typeof ComercialLeadsRoute
  '/financeiro/contas': typeof FinanceiroContasRoute
  '/financeiro/lancamentos': typeof FinanceiroLancamentosRoute
  '/financeiro/projetos': typeof FinanceiroProjetosRoute
  '/orcamentos/$id': typeof OrcamentosIdRoute
  '/orcamentos/novo': typeof OrcamentosNovoRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/biblioteca': typeof BibliotecaIndexRoute
  '/comercial': typeof ComercialIndexRoute
  '/financeiro': typeof FinanceiroIndexRoute
  '/orcamentos': typeof OrcamentosIndexRoute
  '/projetos': typeof ProjetosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/biblioteca': typeof BibliotecaRouteWithChildren
  '/comercial': typeof ComercialRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/contratos': typeof ContratosRoute
  '/crm': typeof CrmRoute
  '/financeiro': typeof FinanceiroRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/orcamentos': typeof OrcamentosRouteWithChildren
  '/performance': typeof PerformanceRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/propostas': typeof PropostasRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/biblioteca/$categoria': typeof BibliotecaCategoriaRoute
  '/comercial/agenda': typeof ComercialAgendaRoute
  '/comercial/contatos': typeof ComercialContatosRoute
  '/comercial/empresas': typeof ComercialEmpresasRoute
  '/comercial/followups': typeof ComercialFollowupsRoute
  '/comercial/leads': typeof ComercialLeadsRoute
  '/financeiro/contas': typeof FinanceiroContasRoute
  '/financeiro/lancamentos': typeof FinanceiroLancamentosRoute
  '/financeiro/projetos': typeof FinanceiroProjetosRoute
  '/orcamentos/$id': typeof OrcamentosIdRoute
  '/orcamentos/novo': typeof OrcamentosNovoRoute
  '/projetos/$id': typeof ProjetosIdRoute
  '/biblioteca/': typeof BibliotecaIndexRoute
  '/comercial/': typeof ComercialIndexRoute
  '/financeiro/': typeof FinanceiroIndexRoute
  '/orcamentos/': typeof OrcamentosIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/biblioteca'
    | '/comercial'
    | '/configuracoes'
    | '/contratos'
    | '/crm'
    | '/financeiro'
    | '/login'
    | '/onboarding'
    | '/orcamentos'
    | '/performance'
    | '/projetos'
    | '/propostas'
    | '/auth/callback'
    | '/biblioteca/$categoria'
    | '/comercial/agenda'
    | '/comercial/contatos'
    | '/comercial/empresas'
    | '/comercial/followups'
    | '/comercial/leads'
    | '/financeiro/contas'
    | '/financeiro/lancamentos'
    | '/financeiro/projetos'
    | '/orcamentos/$id'
    | '/orcamentos/novo'
    | '/projetos/$id'
    | '/biblioteca/'
    | '/comercial/'
    | '/financeiro/'
    | '/orcamentos/'
    | '/projetos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/contratos'
    | '/crm'
    | '/login'
    | '/onboarding'
    | '/performance'
    | '/propostas'
    | '/auth/callback'
    | '/biblioteca/$categoria'
    | '/comercial/agenda'
    | '/comercial/contatos'
    | '/comercial/empresas'
    | '/comercial/followups'
    | '/comercial/leads'
    | '/financeiro/contas'
    | '/financeiro/lancamentos'
    | '/financeiro/projetos'
    | '/orcamentos/$id'
    | '/orcamentos/novo'
    | '/projetos/$id'
    | '/biblioteca'
    | '/comercial'
    | '/financeiro'
    | '/orcamentos'
    | '/projetos'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/biblioteca'
    | '/comercial'
    | '/configuracoes'
    | '/contratos'
    | '/crm'
    | '/financeiro'
    | '/login'
    | '/onboarding'
    | '/orcamentos'
    | '/performance'
    | '/projetos'
    | '/propostas'
    | '/auth/callback'
    | '/biblioteca/$categoria'
    | '/comercial/agenda'
    | '/comercial/contatos'
    | '/comercial/empresas'
    | '/comercial/followups'
    | '/comercial/leads'
    | '/financeiro/contas'
    | '/financeiro/lancamentos'
    | '/financeiro/projetos'
    | '/orcamentos/$id'
    | '/orcamentos/novo'
    | '/projetos/$id'
    | '/biblioteca/'
    | '/comercial/'
    | '/financeiro/'
    | '/orcamentos/'
    | '/projetos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  BibliotecaRoute: typeof BibliotecaRouteWithChildren
  ComercialRoute: typeof ComercialRouteWithChildren
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContratosRoute: typeof ContratosRoute
  CrmRoute: typeof CrmRoute
  FinanceiroRoute: typeof FinanceiroRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  OrcamentosRoute: typeof OrcamentosRouteWithChildren
  PerformanceRoute: typeof PerformanceRoute
  ProjetosRoute: typeof ProjetosRouteWithChildren
  PropostasRoute: typeof PropostasRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/propostas': {
      id: '/propostas'
      path: '/propostas'
      fullPath: '/propostas'
      preLoaderRoute: typeof PropostasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos': {
      id: '/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof OrcamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos': {
      id: '/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof ContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comercial': {
      id: '/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof ComercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof ProjetosRoute
    }
    '/orcamentos/': {
      id: '/orcamentos/'
      path: '/'
      fullPath: '/orcamentos/'
      preLoaderRoute: typeof OrcamentosIndexRouteImport
      parentRoute: typeof OrcamentosRoute
    }
    '/financeiro/': {
      id: '/financeiro/'
      path: '/'
      fullPath: '/financeiro/'
      preLoaderRoute: typeof FinanceiroIndexRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/comercial/': {
      id: '/comercial/'
      path: '/'
      fullPath: '/comercial/'
      preLoaderRoute: typeof ComercialIndexRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/biblioteca/': {
      id: '/biblioteca/'
      path: '/'
      fullPath: '/biblioteca/'
      preLoaderRoute: typeof BibliotecaIndexRouteImport
      parentRoute: typeof BibliotecaRoute
    }
    '/projetos/$id': {
      id: '/projetos/$id'
      path: '/$id'
      fullPath: '/projetos/$id'
      preLoaderRoute: typeof ProjetosIdRouteImport
      parentRoute: typeof ProjetosRoute
    }
    '/orcamentos/novo': {
      id: '/orcamentos/novo'
      path: '/novo'
      fullPath: '/orcamentos/novo'
      preLoaderRoute: typeof OrcamentosNovoRouteImport
      parentRoute: typeof OrcamentosRoute
    }
    '/orcamentos/$id': {
      id: '/orcamentos/$id'
      path: '/$id'
      fullPath: '/orcamentos/$id'
      preLoaderRoute: typeof OrcamentosIdRouteImport
      parentRoute: typeof OrcamentosRoute
    }
    '/financeiro/projetos': {
      id: '/financeiro/projetos'
      path: '/projetos'
      fullPath: '/financeiro/projetos'
      preLoaderRoute: typeof FinanceiroProjetosRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/lancamentos': {
      id: '/financeiro/lancamentos'
      path: '/lancamentos'
      fullPath: '/financeiro/lancamentos'
      preLoaderRoute: typeof FinanceiroLancamentosRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/financeiro/contas': {
      id: '/financeiro/contas'
      path: '/contas'
      fullPath: '/financeiro/contas'
      preLoaderRoute: typeof FinanceiroContasRouteImport
      parentRoute: typeof FinanceiroRoute
    }
    '/comercial/leads': {
      id: '/comercial/leads'
      path: '/leads'
      fullPath: '/comercial/leads'
      preLoaderRoute: typeof ComercialLeadsRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/comercial/followups': {
      id: '/comercial/followups'
      path: '/followups'
      fullPath: '/comercial/followups'
      preLoaderRoute: typeof ComercialFollowupsRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/comercial/empresas': {
      id: '/comercial/empresas'
      path: '/empresas'
      fullPath: '/comercial/empresas'
      preLoaderRoute: typeof ComercialEmpresasRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/comercial/contatos': {
      id: '/comercial/contatos'
      path: '/contatos'
      fullPath: '/comercial/contatos'
      preLoaderRoute: typeof ComercialContatosRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/comercial/agenda': {
      id: '/comercial/agenda'
      path: '/agenda'
      fullPath: '/comercial/agenda'
      preLoaderRoute: typeof ComercialAgendaRouteImport
      parentRoute: typeof ComercialRoute
    }
    '/biblioteca/$categoria': {
      id: '/biblioteca/$categoria'
      path: '/$categoria'
      fullPath: '/biblioteca/$categoria'
      preLoaderRoute: typeof BibliotecaCategoriaRouteImport
      parentRoute: typeof BibliotecaRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BibliotecaRouteChildren {
  BibliotecaCategoriaRoute: typeof BibliotecaCategoriaRoute
  BibliotecaIndexRoute: typeof BibliotecaIndexRoute
}

const BibliotecaRouteChildren: BibliotecaRouteChildren = {
  BibliotecaCategoriaRoute: BibliotecaCategoriaRoute,
  BibliotecaIndexRoute: BibliotecaIndexRoute,
}

const BibliotecaRouteWithChildren = BibliotecaRoute._addFileChildren(
  BibliotecaRouteChildren,
)

interface ComercialRouteChildren {
  ComercialAgendaRoute: typeof ComercialAgendaRoute
  ComercialContatosRoute: typeof ComercialContatosRoute
  ComercialEmpresasRoute: typeof ComercialEmpresasRoute
  ComercialFollowupsRoute: typeof ComercialFollowupsRoute
  ComercialLeadsRoute: typeof ComercialLeadsRoute
  ComercialIndexRoute: typeof ComercialIndexRoute
}

const ComercialRouteChildren: ComercialRouteChildren = {
  ComercialAgendaRoute: ComercialAgendaRoute,
  ComercialContatosRoute: ComercialContatosRoute,
  ComercialEmpresasRoute: ComercialEmpresasRoute,
  ComercialFollowupsRoute: ComercialFollowupsRoute,
  ComercialLeadsRoute: ComercialLeadsRoute,
  ComercialIndexRoute: ComercialIndexRoute,
}

const ComercialRouteWithChildren = ComercialRoute._addFileChildren(
  ComercialRouteChildren,
)

interface FinanceiroRouteChildren {
  FinanceiroContasRoute: typeof FinanceiroContasRoute
  FinanceiroLancamentosRoute: typeof FinanceiroLancamentosRoute
  FinanceiroProjetosRoute: typeof FinanceiroProjetosRoute
  FinanceiroIndexRoute: typeof FinanceiroIndexRoute
}

const FinanceiroRouteChildren: FinanceiroRouteChildren = {
  FinanceiroContasRoute: FinanceiroContasRoute,
  FinanceiroLancamentosRoute: FinanceiroLancamentosRoute,
  FinanceiroProjetosRoute: FinanceiroProjetosRoute,
  FinanceiroIndexRoute: FinanceiroIndexRoute,
}

const FinanceiroRouteWithChildren = FinanceiroRoute._addFileChildren(
  FinanceiroRouteChildren,
)

interface OrcamentosRouteChildren {
  OrcamentosIdRoute: typeof OrcamentosIdRoute
  OrcamentosNovoRoute: typeof OrcamentosNovoRoute
  OrcamentosIndexRoute: typeof OrcamentosIndexRoute
}

const OrcamentosRouteChildren: OrcamentosRouteChildren = {
  OrcamentosIdRoute: OrcamentosIdRoute,
  OrcamentosNovoRoute: OrcamentosNovoRoute,
  OrcamentosIndexRoute: OrcamentosIndexRoute,
}

const OrcamentosRouteWithChildren = OrcamentosRoute._addFileChildren(
  OrcamentosRouteChildren,
)

interface ProjetosRouteChildren {
  ProjetosIdRoute: typeof ProjetosIdRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
}

const ProjetosRouteChildren: ProjetosRouteChildren = {
  ProjetosIdRoute: ProjetosIdRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
}

const ProjetosRouteWithChildren = ProjetosRoute._addFileChildren(
  ProjetosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  BibliotecaRoute: BibliotecaRouteWithChildren,
  ComercialRoute: ComercialRouteWithChildren,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContratosRoute: ContratosRoute,
  CrmRoute: CrmRoute,
  FinanceiroRoute: FinanceiroRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  OrcamentosRoute: OrcamentosRouteWithChildren,
  PerformanceRoute: PerformanceRoute,
  ProjetosRoute: ProjetosRouteWithChildren,
  PropostasRoute: PropostasRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
